name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Unzip and Move Source Code
      run: |
        # १. झिप फाईल अनझिप करणे
        unzip *.zip -d extracted_files
        
        # २. nm14 फोल्डरमधून सर्व फाईल्स मुख्य डिरेक्टरीमध्ये आणणे
        if [ -d "extracted_files/nm14" ]; then
          mv extracted_files/nm14/* . 2>/dev/null || true
          mv extracted_files/nm14/.* . 2>/dev/null || true
        else
          cp -r extracted_files/* . 2>/dev/null || true
          cp -r extracted_files/.* . 2>/dev/null || true
        fi
        rm -rf extracted_files

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
